### ISSUE TITLE
Nickname modal no longer shows warning if validation fails

### ISSUE THREAD

**Issue by calumcb** [banksio/remote-media#24]
When a user does not enter a nickname and either presses return or clicks 'submit' the bootstrap warning pictured below no longer shows.
![image](https://user-images.githubusercontent.com/7143198/86488252-52137500-bd58-11ea-886e-2bc5f01119d8.png)

This may be caused by newly added onsubmit="return false;" inside index.html (reciever view).

**Comment by banksio** [comment]
This is actually a native Chromium dialog. This doesn't seem to be related to the latest commit 6f211cc66818a69662400b887999ce6526d965ab. In fact, it is reproducible as far back as v1.0.0-alpha.1. I'm not sure this was ever implemented. I'm going to look into the form as I need to fix the Enter key bug too.

**Comment by banksio** [comment]
I've resolved this, we now use custom Bootstrap validation styles and override the form's default submission action correctly. The Enter key now works properly without reloading the page so #16 is fixed!
