### ISSUE TITLE
Set resolution 1080p by default

### ISSUE THREAD

**Issue by andrewkliskey** [banksio/remote-media#6]
Hi banksio,

Would it be possible for you, to set the default resolution to 1080p.

Thanks

**Comment by andrewkliskey** [comment]
RUDE!

**Comment by banksio** [comment]
I'll consider this for later versions but it's not on the immediate roadmap right now. I need to refactor the codebase quite urgently.

**Comment by andrewkliskey** [comment]
Thanks old chap!

Much appreciated

**Comment by banksio** [comment]
Unfortunately [YouTube have removed the ability to control the quality of the iframe video](https://developers.google.com/youtube/iframe_api_reference#october-24,-2019), so we don't have any official control over this. If anyone would like to attempt to add a workaround, a pull request is welcome.
